# Generated by Django 3.2.5 on 2021-07-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_alter_employer_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='datefirst',
            field=models.CharField(blank=True, help_text='Дата первой вакцинации', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='datesecond',
            field=models.CharField(blank=True, help_text='Дата второй вакцинации', max_length=20, null=True),
        ),
    ]
