# Generated by Django 3.2.5 on 2021-07-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20210729_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='birthdate',
            field=models.CharField(help_text='Дата рождения', max_length=20),
        ),
        migrations.AlterField(
            model_name='employer',
            name='datefirst',
            field=models.DateField(blank=True, help_text='Дата первой вакцинации', null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='datesecond',
            field=models.DateField(blank=True, help_text='Дата второй вакцинации', null=True),
        ),
    ]
