# Generated by Django 3.2.5 on 2021-07-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_auto_20210729_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='birthdate',
            field=models.CharField(help_text='Дата рождения', max_length=20, null=True),
        ),
    ]
