# Generated by Django 3.2.5 on 2021-07-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_alter_employer_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='vactinationplace',
        ),
        migrations.AddField(
            model_name='employer',
            name='vactinationfull',
            field=models.BooleanField(default=False, help_text='Полная вакцинация'),
        ),
        migrations.AddField(
            model_name='employer',
            name='vactinationplace1',
            field=models.CharField(blank=True, help_text='Место вакцинации 1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='vactinationplace2',
            field=models.CharField(blank=True, help_text='Место вакцинации 2', max_length=100, null=True),
        ),
    ]
