# Generated by Django 3.2.5 on 2021-07-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0006_auto_20210729_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='vactinationplace1',
            field=models.CharField(blank=True, help_text='Место первой вакцинации', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='vactinationplace2',
            field=models.CharField(blank=True, help_text='Место второй вакцинации', max_length=100, null=True),
        ),
    ]
