# Generated by Django 3.2.5 on 2021-07-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0010_alter_employer_vactinationfull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='vactinationfull',
            field=models.BooleanField(default=False, help_text='Полная вакцинация'),
        ),
    ]
