# Generated by Django 3.2.5 on 2021-07-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0011_alter_employer_vactinationfull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='liveplace',
            field=models.TextField(help_text='Место жительства', null=True),
        ),
    ]
