# Generated by Django 3.1.7 on 2021-03-16 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Enter research topic', max_length=500)),
                ('purpose', models.TextField(help_text='Enter purpose of research')),
                ('objectives', models.TextField(help_text='Enter research objectives')),
                ('results', models.TextField(help_text='Enter the planned results')),
                ('scope', models.CharField(help_text='Enter the scope of implementation', max_length=100)),
                ('organization', models.CharField(help_text='Enter the planned organization for implementation', max_length=100)),
                ('explanation', models.TextField(help_text='Explanation of implementation plans', null=True)),
                ('stage', models.CharField(help_text='Explanation of implementation plans', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Enter student's full name", max_length=200)),
                ('category', models.CharField(help_text='Enter student category', max_length=30)),
                ('specialty', models.CharField(help_text="Enter the student's specialty", max_length=50)),
                ('form', models.CharField(help_text='Enter the form of study', max_length=70)),
                ('phone_number', models.CharField(help_text="Enter student's phone number", max_length=18, null=True)),
                ('email', models.CharField(help_text="Enter student's e-mail", max_length=30, null=True)),
                ('date_start', models.DateField(help_text='Start date of study')),
                ('date_end', models.DateField(help_text='End date of study')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Enter teacher's full name", max_length=200)),
                ('degree', models.CharField(help_text="Enter the teacher's degree", max_length=50)),
                ('phone_number', models.CharField(help_text="Enter teacher's phone number", max_length=18, null=True)),
                ('email', models.CharField(help_text="Enter teacher's e-mail", max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('research_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thesis.research')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thesis.student')),
                ('teacher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thesis.teacher')),
            ],
        ),
    ]
