# Generated by Django 3.1.7 on 2021-03-16 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0002_auto_20210316_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='explanation',
            field=models.TextField(help_text='Введите пояснение по планам внедрения (необязательно)', null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='objectives',
            field=models.TextField(help_text='Введите задачи исследования'),
        ),
        migrations.AlterField(
            model_name='research',
            name='organization',
            field=models.CharField(help_text='Введите название организации для внедрения', max_length=100),
        ),
        migrations.AlterField(
            model_name='research',
            name='purpose',
            field=models.TextField(help_text='Введите цель исследования'),
        ),
        migrations.AlterField(
            model_name='research',
            name='results',
            field=models.TextField(help_text='Введите планируемые результаты'),
        ),
        migrations.AlterField(
            model_name='research',
            name='scope',
            field=models.CharField(help_text='Введите планируемую сферу внедрения', max_length=100),
        ),
        migrations.AlterField(
            model_name='research',
            name='stage',
            field=models.CharField(help_text='Введите стадию проработки вопроса о внедрении', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='topic',
            field=models.CharField(help_text='Введите тему исследования', max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(help_text='Введите категорию студента', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_end',
            field=models.DateField(help_text='Дата окончания обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_start',
            field=models.DateField(help_text='Дата начала обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(help_text='Введите электронную почту студента', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='form',
            field=models.CharField(help_text='Введите форму обучения студента', max_length=70),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(help_text='Введите ФИО студента', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(help_text='Введите номер телефона студента', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialty',
            field=models.CharField(help_text='Введите специальность студента', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(help_text='Введите степень руководителя', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(help_text='Введите электронную почту руководителя', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(help_text='Введите ФИО руководителя', max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(help_text='Введите номер телефона руководителя', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(help_text='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='work',
            name='research_id',
            field=models.ForeignKey(help_text='Название работы', null=True, on_delete=django.db.models.deletion.SET_NULL, to='thesis.research'),
        ),
        migrations.AlterField(
            model_name='work',
            name='student_id',
            field=models.ForeignKey(help_text='ФИО студента', null=True, on_delete=django.db.models.deletion.SET_NULL, to='thesis.student'),
        ),
        migrations.AlterField(
            model_name='work',
            name='teacher_id',
            field=models.ForeignKey(help_text='ФИО преподавателя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='thesis.teacher'),
        ),
    ]
