# Generated by Django 3.1.7 on 2021-03-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0004_auto_20210316_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='explanation',
            field=models.TextField(help_text='Введите пояснение по планам внедрения (необязательно)', null=True),
        ),
    ]
