# Generated by Django 3.1.7 on 2021-03-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0005_auto_20210316_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='explanation',
            field=models.TextField(blank=True, help_text='Введите пояснение по планам внедрения (необязательно)', null=True),
        ),
    ]
