# Generated by Django 3.1.7 on 2021-03-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0006_auto_20210316_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, help_text='Введите электронную почту студента', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Введите номер телефона студента', max_length=18, null=True),
        ),
    ]
