# Generated by Django 3.1.7 on 2021-03-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0007_auto_20210316_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='research_id',
            new_name='research',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
