# Generated by Django 3.1.7 on 2021-03-16 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0010_auto_20210316_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='student',
            field=models.OneToOneField(help_text='ФИО студента', null=True, on_delete=django.db.models.deletion.SET_NULL, to='thesis.student'),
        ),
    ]
