# Generated by Django 3.1.7 on 2021-03-16 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0011_auto_20210316_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='date',
            field=models.DateField(blank=True, help_text='Дата добавления', null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='student',
            field=models.OneToOneField(blank=True, help_text='ФИО студента', null=True, on_delete=django.db.models.deletion.SET_NULL, to='thesis.student'),
        ),
        migrations.AddField(
            model_name='research',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='ФИО преподавателя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='thesis.teacher'),
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
