# Generated by Django 3.1.7 on 2021-03-16 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0012_auto_20210316_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='date',
            field=models.DateField(help_text='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='research',
            name='student',
            field=models.OneToOneField(help_text='ФИО студента', null=True, on_delete=django.db.models.deletion.SET_NULL, to='thesis.student'),
        ),
        migrations.AlterField(
            model_name='research',
            name='teacher',
            field=models.ForeignKey(help_text='ФИО преподавателя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='thesis.teacher'),
        ),
    ]
