# Generated by Django 3.1.7 on 2021-03-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0015_auto_20210317_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='research_file',
            field=models.FilePathField(blank=True, null=True, path='/docs'),
        ),
    ]
