# Generated by Django 3.1.7 on 2021-03-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0017_auto_20210330_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='research_file',
            new_name='docfile',
        ),
    ]
