# Generated by Django 3.1.7 on 2021-04-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0021_student_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='form',
            field=models.CharField(blank=True, choices=[('Б', 'Дневная, бюджетная'), ('П', 'Дневная, платная'), ('З', 'Заочная')], help_text='Выберите форму обучения студента', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialty',
            field=models.CharField(blank=True, help_text='Выберите специальность студента', max_length=10, null=True),
        ),
    ]
