# Generated by Django 3.1.7 on 2021-04-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0022_auto_20210405_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='kurs',
            field=models.CharField(blank=True, help_text='Введите курс обучения', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='date',
            field=models.DateField(help_text='Дата начала работы'),
        ),
    ]
