# Generated by Django 3.1.7 on 2021-04-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0025_auto_20210415_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='specialty',
            field=models.CharField(blank=True, help_text='Выберите специальность студента', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('С', 'Студент'), ('М', 'Магистрант'), ('А', 'Аспирант')], default='С', help_text='Категория студента', max_length=1),
        ),
    ]
