# Generated by Django 3.1.7 on 2021-04-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0027_auto_20210415_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='specialty',
            field=models.CharField(blank=True, choices=[('ЭК', 'Экология'), ('МБД', 'Медико-биологическое дело'), ('МФ', 'Медицинская физика'), ('БИ', 'Биоинформатика')], default='ИСТЭ', help_text='Выберите специальность студента', max_length=4, null=True),
        ),
    ]
