# Generated by Django 3.1.7 on 2021-04-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0029_remove_student_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='specialty',
            field=models.CharField(blank=True, choices=[('ИСТЭ', 'Инженер- программист-эколог'), ('ИСТЗ', 'Инженер-программист'), ('ПОД', 'Эколог. Инженер по охране окружающей среды'), ('ЭТЭМ', 'Инженер-энергоменеджер'), ('ЯРБ', 'Инженер'), ('МФ', 'Медицинский физик'), ('ЭК', 'Экология'), ('МБД', 'Медико-биологическое дело'), ('МФ', 'Медицинская физика'), ('БИ', 'Биоинформатика')], default='ИСТЭ', help_text='Выберите специальность студента', max_length=4, null=True),
        ),
    ]
