# Generated by Django 3.1.7 on 2021-04-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0030_student_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='score',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
