# Generated by Django 3.1.7 on 2021-05-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0031_research_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='docfile',
            field=models.FileField(blank=True, help_text='Пояснительная записка', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='research',
            name='score',
            field=models.IntegerField(blank=True, help_text='Введите полученную отметку', null=True),
        ),
    ]
